[package]
name = "jitters"
version = "0.1.0"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
rand = "0.7.0"

[dev-dependencies]
memoffset = "0.5"
hound = "3.4.0"
sample = "0.10.0"
crossbeam = "0.7.2"
